"""Adiciona tabela de historico de interacoes

Revision ID: 9f56e187cc53
Revises: ca70239fa052
Create Date: 2025-08-07 09:40:19.856107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f56e187cc53'
down_revision = 'ca70239fa052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('field_changed', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interaction_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_history_timestamp'))

    op.drop_table('interaction_history')
    # ### end Alembic commands ###
